version: '3.8'

services:
  # 1. The Redis Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 2. The Main Backend API (Now acts as a Modular Monolith)
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env # Pulls your MongoDB URI safely
    environment:
      - REDIS_HOST=redis # This tells Node to talk to the container above
      - BASE_URL=http://localhost:5000
    depends_on:
      - redis

  # 3. The React Frontend
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend